# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "qmix_masked"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

# probability of masking an agent a
mask_prob: 0.3

# same mask for in the same episode
is_sticky: False

# same mask for in the same episode
is_fixed: False

no_state: False

# local_obs_instead_of_state: False
masked_local_obs: False # Can be True only if env_args.obs_instead_of_state is True

name: "qmix_masked"
